# SESSION 9: WORKING WITH DATES AND LUBRIDATE PACKAGE IN R 
# PURPOSE - THE PURPOSE OF THIS SCRIPT IS TO 1) LEARN HOW DATES ARE FORMATTED IN R,
# 2) LEARN HOW TO MANIPULATE AND PRACTICE WORKING WITH DATES AND DATE TIMES IN R

#### INSTALL AND DOWNLOAD PACKAGES ----
#install.packages("tidyverse")
#install.packages("lubridate")
#install.packages("nycflights13)
library(tidyverse)
library(lubridate) # NOTE: IF YOU USE THE "here" PACKAGE, YOU MAY HAVE SOME ISSUES!
library(nycflights13)

lab_birthdays <- read_csv("Session_9/lab_birthdays.csv", 
                          col_names = TRUE)

#### DATE FORMATTING ----
# THERE ARE 3 DIFFERENT TYPES OF DATES WE CAN WORK WITH IN R: DATES, TIMES, AND 
# DATE-TIME
#1) USE "today()" AND "now()" TO SEE THE DIFFERENCE BETWEEN DATES AND DATE-TIMES




# UNFORTUNATELY, SOMETIMES WHEN WE WORK WITH DATES R DOESN'T RECOGNIZE THE VALUE 
# AS A DATE, AND INSTEAD ASSIGNS IT AS A CHARACTER STRING OR NUMERIC VALUE



# THERE ARE A FEW WAYS WE CAN GO ABOUT FIXING THIS: BASE R AND LUBRIDATE
#### BASE R ----
# 2) USE as.Date TO CHANGE "Birthday" FROM A CHARACTER TO A DATE 
# *IF YOU WANTED TO CREATE A DATE-TIME, YOU CAN USE "as.POSIXct" INSTEAD*




# NOTICE HOW "as.Date" ADDS A YEAR TO EACH VALUE...WE CAN TALK ABOUT HOW TO 
# CHANGE THIS LATER

#### LUBRIDATE ----
# LOOK AT R_lubridate.pdf TO SEE ALL OF THE DIFFERENT DATE/DATE-TIME FUNCTIONS AVAILABLE
# 3) DETERMINE WHAT FUNCTION WE NEED IN ORDER TO CHANGE "Birthday" INTO A 
# DATE OBJECT USING THE LUBRIDATE PACKAGE



# BECAUSE THERE ARE NO HOURS, MINUTES, OR SECONDS ASSOCIATED WITH THESE VALUES, IF 
# WE WANT R TO CREATE A DATE-TIME WE HAVE TO INCLUE A TIME ZONE



# WE CAN CHAGNE THE VALUES IN A DATE/DATE-TIME USING THE "update()" FUNCTION IN LUBRIDATE
# 4) USE "update()" TO CHANGE THE YEAR FOR ALL OF THE BIRTHDAYS FROM 2022 TO 2018

lab_birthdays$Birthday <- update(lab_birthdays$Birthday, years = 2018)

#######################################################################################
#######################################################################################

#### CHALLENGE ----
# NOW THAT WE HAVE A BASIC UNDERSTANDING OF HOW THE LUBRIDATE PACKAGE WORKS, LET'S TRY
# SOMETHING A LITTLE MORE CHALLANGING: WHICH AIRPORT HAS THE MOST DELAYED FLIGHTS?

flights <- nycflights13::flights %>%
  select(year, month, day, dep_time, sched_dep_time, 
         arr_time, sched_arr_time, carrier, origin, dest)

# 1) WE CAN'T REALLY DO ANYTHING TO THE DATES AS IS, SO WE NEED TO CREATE DATETIMES FOR: 
    # DEPARTURE TIME
    # SCHEDULED DEPARTURE TIME 
    # ARRIVAL TIME 
    # SCHEDULED ARRIVAL TIME 
# USING "mutate" AND A VERSION OF "make_datetime", LET'S MAKE DATE-TIMES THAT REPRESENT
# THE ABOVE MENTIONED VARIABLES 

make_datetime_100 <- function(year, month, day, time) { # THIS FUNCTION MAKES OUR LIVES A LOT EASIER
  make_datetime(year, month, day, time %/% 100, time %% 100)
}





# 2) NOW THAT WE HAVE THE DATES FORMATTED CORRECTLY, WE WANT TO CALCULATE THE TIME  
# DIFFERENCES BETWEEN "departure_time" AND "scheduled_departure_time" AS WELL AS 
# "arrival_time" AND "scheduled_arrival_time" USING "difftime()" TO CALCULATE THE DELAYS




# 3) SINCE WE HAVE THE DEPARTURE DELAY CALCULATED, TRY TO MAKE A PLOT THAT SHOWS WHICH 
# AIRPORT HAS THE MOST DELAYED FLIGHTS IN THIS DATA SET...IF YOU WANT TO YOU COULD ALSO 
# DO THE SAME FOR ARRIVAL DELAYS 








